import test from 'node:test';
import assert from 'node:assert/strict';
import {endpoint,makeWorkflow,historyFiles,validateGraph} from '../lib/engine.mts';
const input={kind:'image',prompt:'original adult explorer',negative:'blur',seed:123,mode:'fast',aspect:'portrait'};
test('starter SDXL graph uses selected checkpoint, seed, dimensions and sampling settings',()=>{const fast=makeWorkflow(input,{checkpoint:'sdxl.safetensors'});assert.equal(fast['1'].inputs.ckpt_name,'sdxl.safetensors');assert.equal(fast['5'].inputs.seed,123);assert.equal(fast['5'].inputs.steps,20);assert.equal(fast['4'].inputs.width,768);assert.equal(fast['4'].inputs.height,1024);assert.equal(fast['2'].inputs.text,input.prompt);const quality=makeWorkflow({...input,mode:'quality',aspect:'landscape'},{checkpoint:'sdxl.safetensors'});assert.equal(quality['5'].inputs.steps,32);assert.equal(quality['4'].inputs.width,1024);assert.equal(quality['4'].inputs.height,768);});
test('API workflow placeholders preserve links and numeric types without mutating source',()=>{const graph={'1':{class_type:'LoadImage',inputs:{image:'$image'}},'2':{class_type:'LocalVideo',inputs:{text:'$prompt',seed:'$seed',steps:'$steps',frames:'$frames',image:['1',0]}}};const template=JSON.stringify(graph);const result=makeWorkflow({...input,kind:'video',image:'ref.png',mode:'quality'},{template});assert.equal(result['1'].inputs.image,'ref.png');assert.equal(result['2'].inputs.seed,123);assert.equal(result['2'].inputs.frames,81);assert.deepEqual(result['2'].inputs.image,['1',0]);assert.equal(graph['1'].inputs.image,'$image');});
test('unconfigured or invalid workflows cannot pretend to render',()=>{assert.throws(()=>makeWorkflow(input,{}),/checkpoint/);assert.throws(()=>makeWorkflow({...input,kind:'video'},{}),/image-to-video/);assert.throws(()=>validateGraph({nodes:[]}),/API format/);assert.throws(()=>validateGraph({'1':{class_type:'OpenAIImage',inputs:{}}}),/local GPU/);assert.throws(()=>makeWorkflow(input,{template:JSON.stringify({'1':{class_type:'Text',inputs:{text:'$prompt',x:'$unknown'}}})}),/Unknown/);assert.throws(()=>makeWorkflow({...input,kind:'video',image:'ref.png'},{template:JSON.stringify({'1':{class_type:'Text',inputs:{text:'$prompt'}}})}),/\$image/);});
test('proxy preserves endpoint path and rejects untrusted protocols and private addresses',()=>{assert.equal(endpoint('https://gpu.example/proxy/comfy/','history/abc').href,'https://gpu.example/proxy/comfy/history/abc');for(const u of ['http://gpu.example','https://localhost','https://127.1','https://10.0.0.5','https://172.19.1.1','https://192.168.1.1','https://[::1]','https://u:p@gpu.example','https://gpu.example?token=secret'])assert.throws(()=>endpoint(u,'queue'));});
test('history collector supports ComfyUI video combine output and blocks traversal/input files',()=>{const result=historyFiles({outputs:{'1':{images:[{filename:'image.png',subfolder:'JoshBox',type:'output'},{filename:'secret.png',type:'input'},{filename:'../other.png',type:'output'},{filename:'other.png',subfolder:'../secret',type:'output'},{filename:'bad.svg',type:'output'}]},'2':{gifs:[{filename:'clip.mp4',type:'output'},{filename:'loop.gif',type:'output'}]}}});assert.equal(result.length,3);assert.equal(result[0].kind,'image');assert.equal(result[1].kind,'video');assert.equal(result[2].kind,'image');});
