import { and,eq,or,lt } from 'drizzle-orm';
import { getDb } from '@/db';
import { jobs } from '@/db/schema';
import { owner,comfy,bindings,fail,visibleJob,ApiError } from '@/lib/server';
import { historyFiles } from '@/lib/engine.mts';
export const dynamic='force-dynamic';
type Entry={outputs?:Record<string,Record<string,unknown>>;status?:{completed:boolean;status_str:string};prompt?:unknown[]};
export async function GET(_req:Request,{params}:{params:Promise<{id:string}>}){try{
  const userId=await owner();const {id}=await params;const db=getDb();const scope=and(eq(jobs.id,id),eq(jobs.userId,userId));let job=await db.select().from(jobs).where(scope).get();if(!job)throw new ApiError('Job not found.',404);
  if(['complete','failed'].includes(job.status))return Response.json(visibleJob(job),{headers:{'Cache-Control':'no-store'}});
  if(!job.remoteId){const q=await(await comfy('queue')).json() as {queue_running?:unknown[][];queue_pending?:unknown[][]};const hit=[...(q.queue_running??[]),...(q.queue_pending??[])].find(row=>(row[3] as {client_id?:string})?.client_id===id);let remoteId=hit?.[1] as string|undefined;if(!remoteId){const h=await(await comfy('history?max_items=50')).json() as Record<string,Entry>;remoteId=Object.entries(h).find(([,v])=>(v.prompt?.[3] as {client_id?:string})?.client_id===id)?.[0];}if(remoteId){await db.update(jobs).set({remoteId,status:'queued',message:null,updatedAt:Date.now()}).where(scope);job={...job,remoteId,status:'queued',message:null};}else return Response.json(visibleJob(job),{headers:{'Cache-Control':'no-store'}});}
  const history=await(await comfy('history/'+encodeURIComponent(job.remoteId!))).json() as Record<string,Entry>;const entry=history[job.remoteId!];
  if(entry?.status?.status_str==='error'){await db.update(jobs).set({status:'failed',message:'ComfyUI reported an execution error. Check the model, workflow, and GPU memory.',updatedAt:Date.now()}).where(scope);job={...job,status:'failed',message:'ComfyUI reported an execution error. Check the model, workflow, and GPU memory.'};}
  else if(entry?.status?.completed){const files=historyFiles(entry);if(!files.length){await db.update(jobs).set({status:'failed',message:'The workflow finished without a supported saved image or video output.',updatedAt:Date.now()}).where(scope);job={...job,status:'failed',message:'The workflow finished without a supported saved image or video output.'};}
    else{const claim=await db.update(jobs).set({status:'archiving',updatedAt:Date.now()}).where(and(scope,or(eq(jobs.status,'queued'),eq(jobs.status,'running'),and(eq(jobs.status,'archiving'),lt(jobs.updatedAt,Date.now()-120000))))).returning().get();if(!claim)return Response.json(visibleJob({...job,status:'archiving'}));const media=[];
      try{for(const [index,f] of files.entries()){const query=new URLSearchParams({filename:f.filename,subfolder:f.subfolder,type:f.type});const response=await comfy('view?'+query);if(!response.body)throw new Error('Empty output');if(Number(response.headers.get('content-length'))>96*1024**2)throw new Error('Output too large');const ext=f.filename.split('.').pop()!.toLowerCase();const mime:Record<string,string>={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',mp4:'video/mp4',webm:'video/webm'};const key=`${userId}/outputs/${id}/${index}.${ext}`;const length=Number(response.headers.get('content-length'));if(Number.isInteger(length)&&length>0){const stream=new FixedLengthStream(length);await Promise.all([response.body.pipeTo(stream.writable),bindings().BUCKET.put(key,stream.readable,{httpMetadata:{contentType:mime[ext]}})]);}else{let bytes=0;const limited=response.body.pipeThrough(new TransformStream<Uint8Array,Uint8Array>({transform(chunk,controller){bytes+=chunk.length;if(bytes>24*1024**2)throw new Error('Unbounded output too large');controller.enqueue(chunk);}}));await bindings().BUCKET.put(key,await new Response(limited).arrayBuffer(),{httpMetadata:{contentType:mime[ext]}});}media.push({...f,key});}await db.update(jobs).set({status:'complete',media:JSON.stringify(media),message:null,updatedAt:Date.now()}).where(scope);job={...job,status:'complete',media:JSON.stringify(media),message:null};}
      catch{await db.update(jobs).set({status:'running',message:'Output is ready but could not be archived. Keep the GPU running and refresh to retry saving.',updatedAt:Date.now()}).where(scope);job={...job,status:'running',message:'Output is ready but could not be archived. Keep the GPU running and refresh to retry saving.'};}
    }
  }else if(job.status!=='archiving'){const q=await(await comfy('queue')).json() as {queue_running?:unknown[][]};const status=q.queue_running?.some(row=>row[1]===job!.remoteId)?'running':'queued';await db.update(jobs).set({status,updatedAt:Date.now()}).where(scope);job={...job,status};}
  return Response.json(visibleJob(job),{headers:{'Cache-Control':'no-store'}});
}catch(e){return fail(e);}}
