import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { endpoint } from './engine.mts';
export function bindings(){return env as unknown as {DB:D1Database;BUCKET:R2Bucket;COMFY_URL?:string;COMFY_TOKEN?:string;COMFY_AUTH_HEADER?:string;COMFY_CHECKPOINT?:string;COMFY_IMAGE_WORKFLOW?:string;COMFY_VIDEO_WORKFLOW?:string;COMFY_VIDEO_WORKFLOW_FAST?:string;COMFY_VIDEO_WORKFLOW_QUALITY?:string;VIDEO_PROXY_URL?:string;VIDEO_PROXY_TOKEN?:string};}
export function videoConfig(){const c=bindings();return {template:c.COMFY_VIDEO_WORKFLOW,fastTemplate:c.COMFY_VIDEO_WORKFLOW_FAST,qualityTemplate:c.COMFY_VIDEO_WORKFLOW_QUALITY};}
export class ApiError extends Error{constructor(message:string,public status=400,public upstreamStatus?:number){super(message);}}
export async function owner(request?:Request){const user=await getChatGPTUser();if(!user)throw new ApiError('Sign in to your private studio.',401);if(request&&request.method!=='GET'&&request.headers.get('origin')!==new URL(request.url).origin)throw new ApiError('This request must come from your studio.',403);return user.userId;}
export function fail(e:unknown){if(e instanceof ApiError)return Response.json({error:e.message},{status:e.status});if(e instanceof Error&&(e.name==='ZodError'||e.name==='SyntaxError'))return Response.json({error:'Please check the inputs and try again.'},{status:400});return Response.json({error:'The studio could not complete this request. Try refreshing.'},{status:500});}
export async function json(request:Request){const text=await request.text();if(text.length>16000)throw new ApiError('The request is too large.',413);return JSON.parse(text);}
export async function comfy(path:string,init:RequestInit={}){
  const config=bindings();if(!config.COMFY_URL||!config.COMFY_TOKEN)throw new ApiError('Your GPU is not connected yet. Open Connection for the setup checklist.',503);let url:URL;try{url=endpoint(config.COMFY_URL,path);}catch{throw new ApiError('The GPU endpoint needs a valid public HTTPS address.',503);}const headers=new Headers(init.headers);
  if(config.COMFY_TOKEN){const name=config.COMFY_AUTH_HEADER||'Authorization';if(!['Authorization','X-API-Key'].includes(name))throw new ApiError('Unsupported GPU authentication header.',503);headers.set(name,name==='Authorization'?`Bearer ${config.COMFY_TOKEN}`:config.COMFY_TOKEN);}
  let result:Response;try{result=await fetch(url,{...init,headers,redirect:'error',signal:AbortSignal.timeout(20000)});}catch{throw new ApiError('The GPU did not respond. Check its running state, HTTPS certificate, and connection.',502);}if(!result.ok){const msg=result.status===401||result.status===403?'The GPU rejected its access token.':result.status===400?'ComfyUI rejected the workflow. Check installed models, nodes, and workflow inputs.':'The GPU returned an error. Check ComfyUI on the instance.';throw new ApiError(msg,502,result.status);}return result;
}
export function visibleJob(j:Record<string,unknown>){return {id:j.id,kind:j.kind,prompt:j.prompt,negative:j.negative,mode:j.mode,aspect:j.aspect,seed:j.seed,duration:j.duration??null,parentJobId:j.parentJobId??null,backend:String(j.remoteId??'').startsWith('proxy:')?'proxy':'comfy',status:j.status,message:j.message,createdAt:j.createdAt,media:JSON.parse(j.media as string||'[]').map((m:{kind:string;filename:string})=>({kind:m.kind,filename:m.filename}))};}
