import { z } from 'zod';
import { and,eq } from 'drizzle-orm';
import { getDb } from '@/db';
import { jobs,characters } from '@/db/schema';
import { makeWorkflow } from '@/lib/engine.mts';
import { owner,json,fail,bindings,comfy,ApiError,visibleJob,videoConfig } from '@/lib/server';
const schema=z.object({requestId:z.string().uuid(),kind:z.enum(['image','video']),prompt:z.string().trim().min(8).max(3000),negative:z.string().max(1500).default(''),mode:z.enum(['fast','quality']),aspect:z.enum(['portrait','square','landscape']),duration:z.union([z.literal(5),z.literal(10),z.literal(15)]).optional(),seed:z.number().int().min(0).max(2147483647),adultOnly:z.literal(true),characterId:z.string().uuid().optional(),sourceJobId:z.string().uuid().optional(),sourceIndex:z.number().int().min(0).max(7).optional(),extendJobId:z.string().uuid().optional(),extendIndex:z.number().int().min(0).max(7).optional(),uploadId:z.string().uuid().optional()});
export async function POST(request:Request){try{
  const userId=await owner(request);const input=schema.parse(await json(request));const db=getDb();const c=bindings();const prior=await db.select().from(jobs).where(and(eq(jobs.id,input.requestId),eq(jobs.userId,userId))).get();if(prior)return Response.json(visibleJob(prior));
  let prompt=input.prompt;if(input.characterId){const person=await db.select().from(characters).where(and(eq(characters.id,input.characterId),eq(characters.userId,userId))).get();if(!person)throw new ApiError('Character not found.',404);prompt=`Fictional adult age 25 or older. ${person.description}. ${prompt}`;}
  if(input.extendJobId){if(input.kind!=='video'||!input.uploadId||input.sourceJobId)throw new ApiError('An extension needs the saved video and its extracted final frame.');const parent=await db.select().from(jobs).where(and(eq(jobs.id,input.extendJobId),eq(jobs.userId,userId))).get();const media=parent?JSON.parse(parent.media):[];if(parent?.status!=='complete'||media[input.extendIndex??0]?.kind!=='video')throw new ApiError('Choose a saved video from your own gallery.',404);}
  if(!c.COMFY_URL||!c.COMFY_TOKEN)throw new ApiError('Your GPU is not connected yet. Open Settings to see what is needed.',503);
  let source:R2ObjectBody|null=null;if(input.kind==='video'){if(input.sourceJobId){const src=await db.select().from(jobs).where(and(eq(jobs.id,input.sourceJobId),eq(jobs.userId,userId))).get();const media=src?JSON.parse(src.media):[];const file=media[input.sourceIndex??0];if(src?.status!=='complete'||!file||file.kind!=='image')throw new ApiError('Choose a saved image to animate.');source=await c.BUCKET.get(file.key);}else if(input.uploadId)source=await c.BUCKET.get(`${userId}/inputs/${input.uploadId}`);if(!source)throw new ApiError('Upload an image or choose one from your gallery.');if(source.size>12*1024**2)throw new ApiError('Choose a reference image smaller than 12 MB.',413);}
  const workflowConfig=input.kind==='video'?videoConfig():{checkpoint:c.COMFY_CHECKPOINT,template:c.COMFY_IMAGE_WORKFLOW};let graph;try{graph=makeWorkflow({...input,prompt,image:source?'pending.png':undefined},workflowConfig);}catch(e){throw new ApiError(e instanceof Error?e.message:'The workflow needs configuration.',503);}
  if(source){const form=new FormData();form.append('image',new File([await source.arrayBuffer()],`${input.requestId}.${source.httpMetadata?.contentType==='image/jpeg'?'jpg':source.httpMetadata?.contentType==='image/webp'?'webp':'png'}`,{type:source.httpMetadata?.contentType||'image/png'}));form.append('overwrite','false');const up=await(await comfy('upload/image',{method:'POST',body:form})).json() as {name:string;subfolder?:string};if(typeof up.name!=='string'||!up.name)throw new ApiError('The GPU did not confirm the image upload.',502);graph=makeWorkflow({...input,prompt,image:up.subfolder?`${up.subfolder}/${up.name}`:up.name},workflowConfig);}
  const row={id:input.requestId,userId,kind:input.kind,prompt,negative:input.negative,mode:input.mode,aspect:input.aspect,seed:input.seed,duration:input.kind==='video'?input.duration??null:null,parentJobId:input.extendJobId??null,status:'submitting',createdAt:Date.now(),updatedAt:Date.now(),media:'[]',message:null,remoteId:null};try{await db.insert(jobs).values(row);}catch{throw new ApiError('You already have an active generation. Check Activity before starting another.',409);}
  try{const result=await(await comfy('prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:graph,client_id:input.requestId})})).json() as {prompt_id?:string};if(!result.prompt_id)throw new ApiError('ComfyUI did not return a job ID. Check the workflow.',502);const updated={...row,status:'queued',remoteId:result.prompt_id};await db.update(jobs).set({status:'queued',remoteId:result.prompt_id,updatedAt:Date.now()}).where(eq(jobs.id,row.id));return Response.json(visibleJob(updated),{status:201});
  }catch(e){const message=e instanceof ApiError?e.message:'Submission could not be confirmed. Check the ComfyUI queue.';const rejected=e instanceof ApiError&&!!e.upstreamStatus&&[400,401,403,404,422].includes(e.upstreamStatus);await db.update(jobs).set({status:rejected?'failed':'uncertain',message,updatedAt:Date.now()}).where(eq(jobs.id,row.id));throw new ApiError(rejected?message:`${message} Submission is unconfirmed; do not retry until the GPU queue has been checked.`,502);}
}catch(e){return fail(e);}}
